### ISSUE TITLE
cluster bootstrap

### ISSUE THREAD

**Issue by pgte** [pgte/skiff#11]
https://github.com/pgte/skiff/tree/master#cluster-setup

Discuss.

**Comment by AVVS** [comment]
I personally don't like this approach as it requires me to manually bootstrap the cluster instead of specifying a basic configuration of ip addresses and ports for each of the nodes for ability to bootstrap them automatically later on. Any way we can implement pre-configured cluster?

**Comment by pgte** [comment]
v1.0 is using pre-configured cluster and an optional asynchronous .join (with joint consensus).
