### ISSUE TITLE
how about fault tolerance?

### ISSUE THREAD

**Issue by kon5t** [pgte/skiff#19]
Win7 x64. I run skiff in three consoles with different ip ports and databases (2 processes with `standby: true`). When I kill one process, the other two die with the following message:
```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: read ECONNRESET
    at errnoException (net.js:904:11)
    at TCP.onread (net.js:558:19)
```

**Comment by pgte** [comment]
Yes, this is a flaw on the current implementation because of the way peer connections are handled. I intend to address this by overhauling the backend. I plan to start working on this in the next montho or two.

**Comment by pgte** [comment]
See #24
