### ISSUE TITLE
redis-backed skiff implementation

### ISSUE THREAD

**Issue by AVVS** [pgte/skiff#20]
I've just finished rewriting this modules and now we have a version that can use redis anything as a backend (sentinel configuration, cluster configuration, just a single node configuration).

https://github.com/AVVS/skiff-redis - tests were basically cloned with minor changes and pass at this point.

I couldnt use redisDOWN backend for skiff-level, because it doesn't support HA solutions for redis (as node_redis module wasn't updated for a long time now)

Any thoughts appreciated, thx

**Comment by pgte** [comment]
For 1.0 the backend interface should be leveldown. See #24.
