### ISSUE TITLE
Some examples?

### ISSUE THREAD

**Issue by tailiu** [pgte/skiff#21]
Hi, I wonder how to get a simple example using the API provided? In the example:
1.Several nodes join a cluster.
2.One node is selected to be the only leader of the cluster.
3.After proposal, finally a value is chosen and learnt by the leader, Leader tells the result to all the nodes.
Can anybody tell me how to build such a simple example to have a basic understanding of the skiff code?

**Comment by pgte** [comment]
Please see the `test` folder, it has many examples.
Also, I recommend learning [the Raft protocol](https://raft.github.io/) if you haven't yet.
