### ISSUE TITLE
Is this now abadonware?

### ISSUE THREAD

**Issue by delaneyj** [pgte/skiff#23]
* Does not currently build in windows
* Way behind in versioning 
* Issues aren't being responded to.  

Do you consider this project abadonware at this point?

**Comment by pgte** [comment]
This is a passion project and something I don't depend (neither recommend) using it on production.
Yes, the work on this was interrrupted.
No, I don't intend to abandon it.
I plan to return to this with an overhaul API and implementation, beginning work on this on January next year, if everything goes according to planned.

(Also, I may need some help. If you're interested in contributing, hit me up on email or something.)

**Comment by delaneyj** [comment]
Thanks @pgte for the response.  I was interesting in doing a project using CQRS/EventSourcing and idea of only a single point for commands (writes) but scaling reads works perfectly with a leveldb/raft combo.  I saw that your project seem to be a good deal of the way there but hadn't been worked on actively in a while.  I'm not in a hurry to rely on it right now but long term would need to implement something like skiff anyway.  What are your plans for the revamp of API & implementation?

**Comment by pgte** [comment]
@delaneyj I've summed up my biggest pain points here: https://github.com/pgte/skiff/issues/24
