### ISSUE TITLE
Proxy levelup commands to leader

### ISSUE THREAD

**Issue by delaneyj** [pgte/skiff#40]
I want the levelup commands to proxy to the leader but unsure given the documentation.
[The README](https://github.com/pgte/skiff#skifflevelup-) says 
> Node must be a leader in order to accept commands.

but [the remote tests show otherwise](https://github.com/pgte/skiff/blob/master/test/remote-commands.js).  Which is the expected behavior?

**Comment by pgte** [comment]
That part of the documentation is outdated.
The expected behaviour is that, when a node is not the leader and it knows of a leader, it forwards the command to the leader node.

**Comment by delaneyj** [comment]
Awesome!  Thanks for the fast response and update to the docs.
